name: sqlproj-sample

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build mssqlproj.sqlproj

    - name: Install
      run: dotnet tool install -g Microsoft.SqlPackage 

    - name: two
      run: dotnet new install Microsoft.Build.Sql.Templates
      
    - name: Deploy
      run: sqlpackage /Action:Publish /SourceFile:bin/Debug/mssqlproj.dacpac /TargetConnectionString:'Server=tcp:testserverdevops.database.windows.net;Initial Catalog=sqldevops;User ID=djamel;Password=Abcd+1234' /p:AllowIncompatiblePlatform=true;      #uses: azure/sql-action@v2.3
      #with:
        #connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
        #action: 'publish'
        #path: 'bin/Debug/mssqlproj.dacpac'
        #arguments: '/p:AllowIncompatiblePlatform=true'
